'use client';

import { useEffect, useState } from 'react';
import { VERTICALS } from '@/data/verticals';

// The Collector Pulse — an EKG strip reading real catalog breadth off
// public/traffic/market-pulse.json (generated by scripts/grailpulse-traffic-pulse.mjs).
// Client-only by design: nothing here is in the LCP path, and if the fetch or
// parse fails, the section renders nothing rather than a stale/fabricated
// strip. One catalog pick per live vertical per day (date-seeded, not
// random) so the pick is stable across a visit but changes daily. GrailGamer
// has no data source (its own pipeline is known-red) and stays unlinked and
// count-free — its spike is a softened "coming soon" placeholder only.

type MarketPulseSite = {
  key: string;
  priorityUrls: string[];
};

type MarketPulseData = {
  generatedAt: string;
  sites: MarketPulseSite[];
};

type PulsePick = { label: string; url: string };

const UTILITY_FIRST_SEGMENTS = new Set([
  'browse',
  'garage',
  'methodology',
  'trust',
  'privacy',
  'terms',
  'search',
  'news',
  'about',
  'verticals',
  'coin',
]);

function humanize(slug: string): string {
  return slug
    .split(/[-_]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function labelForUrl(siteKey: string, url: string): string | null {
  let path: string;
  try {
    path = new URL(url).pathname.replace(/^\/+|\/+$/g, '');
  } catch {
    return null;
  }
  const parts = path.split('/').filter(Boolean);
  if (parts.length === 0) return null;

  if (siteKey === 'coins' && parts[0] === 'series' && parts[1]) {
    return humanize(parts[1]);
  }
  if (siteKey === 'diecast' && parts[0] === 'series' && parts[1]) {
    const segments = parts[1].split('__');
    return humanize(segments[segments.length - 1]);
  }
  if (siteKey === 'figures') {
    if (UTILITY_FIRST_SEGMENTS.has(parts[0])) return null;
    return humanize(parts[parts.length - 1]);
  }
  return null;
}

/** UTC day-of-year — deterministic per calendar day, not per render. */
function dayOfYear(date: Date): number {
  const start = Date.UTC(date.getUTCFullYear(), 0, 1);
  const today = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  return Math.floor((today - start) / 86400000);
}

export function CollectorPulse() {
  const [picks, setPicks] = useState<Record<string, PulsePick> | null>(null);
  const [syncedAt, setSyncedAt] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/traffic/market-pulse.json')
      .then((res) => (res.ok ? (res.json() as Promise<MarketPulseData>) : null))
      .then((data) => {
        if (cancelled || !data) return;
        const seed = dayOfYear(new Date());
        const nextPicks: Record<string, PulsePick> = {};
        for (const site of data.sites) {
          const seen = new Set<string>();
          const pool: PulsePick[] = [];
          for (const url of site.priorityUrls) {
            const label = labelForUrl(site.key, url);
            if (label && !seen.has(label)) {
              seen.add(label);
              pool.push({ label, url });
            }
          }
          if (pool.length) nextPicks[site.key] = pool[seed % pool.length];
        }
        setPicks(nextPicks);
        setSyncedAt(data.generatedAt);
      })
      .catch(() => {
        // Fetch/parse failure: render nothing rather than a broken strip.
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (!picks) return null;

  const syncedLabel = syncedAt
    ? new Date(syncedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
    : null;

  return (
    <section className="gp-pulse" aria-label="The Collector Pulse — today's catalog picks across GrailPulse">
      <div className="gp-shell gp-pulse__inner">
        <div className="gp-pulse__head">
          <p className="gp-eyebrow">The Collector Pulse</p>
          {syncedLabel && <p className="gp-pulse__synced">Last synced {syncedLabel}</p>}
        </div>

        <div className="gp-pulse__strip" aria-hidden="true">
          <div className="gp-pulse__track">
            <PulseWave />
            <PulseWave />
          </div>
          <span className="gp-pulse__scanline" />
        </div>

        <ul className="gp-pulse__chips">
          {VERTICALS.map((v) => {
            const soon = v.status === 'soon';
            const pick = picks[v.key];
            const row = (
              <>
                <span className="gp-pulse__chip-dot" aria-hidden="true" />
                <span className="gp-pulse__chip-name">{v.name}</span>
                <span className="gp-pulse__chip-label">
                  {soon ? 'Catalog coming soon' : pick?.label ?? 'Tracking the catalog'}
                </span>
              </>
            );
            return (
              <li
                className={`gp-pulse__chip${soon ? ' is-soon' : ''}`}
                key={v.key}
                style={{ ['--pulse-accent' as never]: v.accent }}
              >
                {!soon && pick ? (
                  <a className="gp-pulse__chip-row" href={pick.url}>
                    {row}
                  </a>
                ) : (
                  <span className="gp-pulse__chip-row">{row}</span>
                )}
              </li>
            );
          })}
        </ul>
      </div>
    </section>
  );
}

function PulseWave() {
  const spikeX = [60, 160, 260, 360];
  return (
    <svg className="gp-pulse__wave" viewBox="0 0 400 80" preserveAspectRatio="none" aria-hidden="true">
      <path className="gp-pulse__baseline" d="M0,40 L400,40" />
      {VERTICALS.map((v, i) => {
        const cx = spikeX[i];
        // spikeX only has 4 slots — a 5th vertical would produce an
        // undefined cx and a broken path, so skip rather than render one.
        if (cx == null) return null;
        const d = `M${cx - 20},40 L${cx - 8},40 L${cx - 4},15 L${cx},65 L${cx + 4},30 L${cx + 8},40 L${cx + 20},40`;
        return (
          <path
            key={v.key}
            className={`gp-pulse__spike${v.status === 'soon' ? ' is-soon' : ''}`}
            d={d}
            style={{ stroke: v.accent }}
          />
        );
      })}
    </svg>
  );
}
